name: Check secrets
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check secrets
        env:
          REPO_SECRET: ${{ secrets.SECRET }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "$REPO_SECRET" |
          echo "$SECRETS"