name: Check secrets
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: check secrets
        env:
          SECRETS: ${{ toJSON(secrets) }}

        run: |
          echo "$SECRETS"
  check-staging:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: check secrets
        env:
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "$SECRETS"